-- =====================================================================
-- 组合方案（Motion Recipe）种子：25 套新方案 + 5 套既有方案（补上步骤）
--
-- 生成器：_gh/mr_build.py（数据源 _gh/mr_data.py）—— 不要手改本文件，改数据后重跑生成器。
-- 幂等：按 recipe_key upsert，重跑只刷新方案本身，不动人工评分（motion_rating 单独一张表）。
-- 依赖：motion_recipe.steps 列（见 db/extensions_motion_recipe.sql）。
-- =====================================================================

USE `kingdom_studio`;

SET NAMES utf8mb4;

-- ---------------------------------------------------------------------
-- 组合方案：每个方案是一串按应用顺序排列的步骤，每一步带
--   templateKey 用哪个模板 / stage 负责哪一层 / role 这一步的作用
-- score 是按成员实时算出来的缓存值，服务端每次都重算（与模板列表口径一致）。
-- ---------------------------------------------------------------------
INSERT INTO `motion_recipe`
	(`recipe_key`, `name`, `description`, `scene`, `style`, `best_for`, `score`,
	 `template_keys`, `steps`, `prompt`, `status`)
VALUES
	('apple-product-page', 'Apple Product Page', '苹果式产品页：先让页面安静下来，再用一句标题、一次滚动、一张卡片把注意力收到产品上。', 'Landing Page', 'Minimal', '官网首页,产品页', 91, '["smooth-fade", "slide-up", "scroll-reveal", "pricing-card-hover"]', '[{"templateKey": "smooth-fade", "stage": "背景", "role": "整页容器先柔和淡入，避免首帧闪一下"}, {"templateKey": "slide-up", "stage": "内容", "role": "主标题与副标题上滑淡入，一次只动一个层级"}, {"templateKey": "scroll-reveal", "stage": "滚动", "role": "向下滚动时逐块点亮，讲解顺序由滚动控制"}, {"templateKey": "pricing-card-hover", "stage": "交互", "role": "规格或版本对比卡带上浮悬停，把差异讲清楚"}]', '做一个苹果风格的产品页：整页柔和淡入，主标题上滑出现；向下滚动时各内容块逐级点亮，规格卡悬停时轻微上浮并加深投影。全程只使用 transform / opacity，滚动动画只在元素进入视口时触发一次，不重复播放。', 'READY'),
	('luxury-hotel', 'Luxury Hotel', '高级酒店官网：颗粒底纹压住廉价感，幕布式开场拉出空间，再用视差与磁吸按钮收尾。', 'Landing Page', 'Luxury', '高级酒店官网,品牌官网', 90, '["grain-overlay-bg", "hero-split-curtain", "split-char-rise", "parallax-depth-3", "magnetic-pull-btn"]', '[{"templateKey": "grain-overlay-bg", "stage": "背景", "role": "叠一层极细颗粒，避免大面积渐变显得发灰"}, {"templateKey": "hero-split-curtain", "stage": "内容", "role": "首屏像幕布一样从中间分开，先给空间再给内容"}, {"templateKey": "split-char-rise", "stage": "内容", "role": "品牌名逐字上升，节奏比整块淡入更慢更贵"}, {"templateKey": "parallax-depth-3", "stage": "滚动", "role": "三层视差让画面在滚动时有纵深"}, {"templateKey": "magnetic-pull-btn", "stage": "收尾", "role": "预订按钮带磁吸，提示这是主行动点"}]', '做一个高级酒店官网首屏：背景铺一层细腻颗粒纹理，首屏用幕布分屏方式打开；品牌名逐字上升出现；滚动时背景 / 中景 / 前景三层以不同速度位移；主按钮带磁吸效果。整体节奏要慢，单步动效不低于 0.8 秒。', 'READY'),
	('cyber-launch', 'Cyber Launch', '科技感发布页：星系底 + 星空漂移铺满屏幕，标题擦除进入，按钮在悬停时给出金属触感。', 'Landing Page', 'Cyber', '科技感首页,发布会页', 90, '["galaxy-background", "starfield-drift-bg", "headline-clip-wipe", "magnetic-button"]', '[{"templateKey": "galaxy-background", "stage": "背景", "role": "星系渐变打底，给整页定下冷色调"}, {"templateKey": "starfield-drift-bg", "stage": "背景", "role": "星空缓慢漂移，让静止画面也不死板"}, {"templateKey": "headline-clip-wipe", "stage": "内容", "role": "标题从左到右擦除出现，比淡入更有发布感"}, {"templateKey": "magnetic-button", "stage": "收尾", "role": "主按钮磁吸跟随指针，引导点击"}]', '做一个科技感发布页：背景是缓慢旋转的星系渐变，上面叠一层缓慢漂移的星空；主标题用 clip-path 从左侧擦除出现；主按钮磁吸。整体冷色、克制，不要发光过曝。', 'READY'),
	('scroll-story', 'Scroll Story', '长页叙事：进度条告诉用户走到哪，分屏钉住讲一段，剩下的交给滚动逐级点亮。', 'Landing Page', 'Minimal', '长页叙事,品牌故事页', 90, '["scroll-progress-bar", "sticky-pin-panel", "scroll-reveal", "text-reveal"]', '[{"templateKey": "scroll-progress-bar", "stage": "滚动", "role": "顶部进度条让长页有「还有多少」的预期"}, {"templateKey": "sticky-pin-panel", "stage": "内容", "role": "关键一段钉住不动，让文案自己走完"}, {"templateKey": "scroll-reveal", "stage": "滚动", "role": "其余内容进入视口时逐级点亮"}, {"templateKey": "text-reveal", "stage": "收尾", "role": "结尾用一句揭示式文案收住"}]', '做一个长页叙事页面：顶部有滚动进度条；中间用 sticky 钉住一个分屏，让文字在固定画面里逐段替换；其余内容块进入视口时逐级点亮；结尾一句话用揭示方式出现。滚动动效一律使用 IntersectionObserver，只触发一次。', 'READY'),
	('organic-brand', 'Organic Brand', '治愈系品牌页：流体质感渐变打底，内容用模糊恢复的方式慢慢显影，卡片保持轻微浮动。', 'Landing Page', 'Organic', '品牌官网,生活方式页', 90, '["liquid-gradient", "blur-focus-in", "floating-card", "arrow-swipe-btn"]', '[{"templateKey": "liquid-gradient", "stage": "背景", "role": "流体质感渐变让画面像一直在轻轻呼吸"}, {"templateKey": "blur-focus-in", "stage": "内容", "role": "文案从模糊恢复到清晰，比淡入更柔和"}, {"templateKey": "floating-card", "stage": "内容", "role": "内容卡静止时轻微上下浮动，去掉生硬边界"}, {"templateKey": "arrow-swipe-btn", "stage": "交互", "role": "按钮用横向滑动给反馈，克制但明确"}]', '做一个治愈系品牌页：背景是缓慢流动的流体渐变；标题与段落从 blur(10px) 恢复到清晰；内容卡静止时以 6 秒周期轻微上下浮动 6px；按钮悬停时箭头横向滑出。整体节奏舒缓，不要出现硬切。', 'READY'),
	('ai-model-launch', 'AI Model Launch', '模型发布页：网格渐变底 + 粒子星网给纵深，标题擦除进入，能力卡用流光描边提示可交互。', 'AI SaaS', 'Cyber', 'AI 产品页,模型发布页', 89, '["mesh-gradient", "particle-network", "headline-clip-wipe", "glow-border", "glow-pulse-cta"]', '[{"templateKey": "mesh-gradient", "stage": "背景", "role": "网格渐变打底，科技感来自结构而不是特效"}, {"templateKey": "particle-network", "stage": "背景", "role": "粒子星网给画面纵深，暗示「网络 / 连接」"}, {"templateKey": "headline-clip-wipe", "stage": "内容", "role": "模型名擦除出现，配合一次轻微上移"}, {"templateKey": "glow-border", "stage": "交互", "role": "能力卡悬停时边框流光，提示可以点开"}, {"templateKey": "glow-pulse-cta", "stage": "收尾", "role": "主 CTA 呼吸发光，把转化点放在最后一屏"}]', '做一个 AI 模型发布页：背景用网格渐变 + 粒子星网两层叠加；模型名用 clip-path 横向擦除出现；三项能力卡悬停时边框流光扫过；主 CTA 按钮以 2.6 秒周期呼吸发光。粒子数量不超过 60，移动端降到 30。', 'READY'),
	('ai-analytics-product', 'AI Analytics Product', '数据智能产品页：模糊恢复的文案 + 浮动光球当视觉锚点，卡片用光斑跟随强调「智能」。', 'AI SaaS', 'Glass', 'AI 产品页,数据产品页', 88, '["blur-reveal", "floating-orb", "spotlight-card", "modal-morph"]', '[{"templateKey": "blur-reveal", "stage": "内容", "role": "说明文案从模糊恢复，像镜头对焦"}, {"templateKey": "floating-orb", "stage": "背景", "role": "一颗浮动光球当整页的视觉锚点"}, {"templateKey": "spotlight-card", "stage": "交互", "role": "指针靠近卡片时亮起光斑，强调可探索"}, {"templateKey": "modal-morph", "stage": "收尾", "role": "点开示例时用形变弹窗，不打断上下文"}]', '做一个 AI 数据分析产品页：顶部说明文案从 blur 恢复到清晰；画面中有一颗缓慢上下浮动的光球作为视觉锚点；能力卡在指针靠近时出现跟随光斑；点击「看示例」时用形变方式打开弹窗。整体透明度层次要清楚，不要堆叠过多模糊。', 'READY'),
	('ai-wellness', 'AI Wellness', 'AI 健康产品页：融合球与漂移网格给「活着的」感觉，渐变文字承担品牌语气。', 'AI SaaS', 'Organic', 'AI 产品页,健康类产品', 89, '["canvas-metaball", "mesh-drift-bg", "gradient-text-flow", "glow-pulse-cta"]', '[{"templateKey": "canvas-metaball", "stage": "背景", "role": "融合球缓慢变形，暗示数据在流动"}, {"templateKey": "mesh-drift-bg", "stage": "背景", "role": "网格渐变漂移，和融合球形成两层纵深"}, {"templateKey": "gradient-text-flow", "stage": "内容", "role": "品牌主张用渐变流动，替代普通标题"}, {"templateKey": "glow-pulse-cta", "stage": "收尾", "role": "CTA 呼吸发光，给页面一个温和的落点"}]', '做一个 AI 健康产品页：背景用 Canvas 融合球 + 漂移网格两层；品牌主张用渐变文字缓慢流动；主 CTA 以 3 秒周期呼吸发光。整体柔和不刺眼，动画帧率优先保证 60fps，粒子与模糊半径按屏幕缩放。', 'READY'),
	('designer-portfolio', 'Designer Portfolio', '设计师作品集：颗粒底 + 缩放揭示，滚动时作品以不同速度掠过，卡片悬停浮起。', 'Portfolio', 'Luxury', '个人作品集,设计师主页', 91, '["grain-overlay-bg", "scale-reveal", "parallax-depth-3", "glass-lift-hover"]', '[{"templateKey": "grain-overlay-bg", "stage": "背景", "role": "颗粒质感让整页更像印刷品而不是网页"}, {"templateKey": "scale-reveal", "stage": "内容", "role": "首个作品从 0.92 放大浮现，先给一个「作品」信号"}, {"templateKey": "parallax-depth-3", "stage": "滚动", "role": "作品图分批以不同速度移动，制造层次"}, {"templateKey": "glass-lift-hover", "stage": "交互", "role": "作品卡悬停时上浮并加深投影"}]', '做一个设计师作品集：整页叠一层细颗粒；首个作品从 0.92 缩放浮现；滚动时作品图分三层以 0.85 / 1.0 / 1.15 的速度位移；作品卡悬停上浮 8px。整体留白要大，动效只为作品服务。', 'READY'),
	('photographer-gallery', 'Photographer Gallery', '摄影画廊：照片从模糊对焦进来，滚动视差让画面连续，翻面卡用来放拍摄信息。', 'Portfolio', 'Minimal', '摄影作品集,画廊', 89, '["blur-focus-in", "image-parallax", "flip-reveal-card", "cursor-follow"]', '[{"templateKey": "blur-focus-in", "stage": "内容", "role": "照片从失焦到清晰，像镜头对焦"}, {"templateKey": "image-parallax", "stage": "滚动", "role": "滚动时照片与说明以不同速度移动"}, {"templateKey": "flip-reveal-card", "stage": "交互", "role": "翻面卡放拍摄参数，不打断浏览节奏"}, {"templateKey": "cursor-follow", "stage": "收尾", "role": "光标跟随一团柔光，代替传统指针"}]', '做一个摄影作品集：每张照片进入视口时从 blur(14px) 恢复到清晰；滚动时照片与说明文字以不同速度位移；点击照片翻面显示拍摄参数；鼠标移动时有一团柔光跟随。整体以图片为主，动效克制。', 'READY'),
	('developer-homepage', 'Developer Homepage', '开发者主页：星空底 + 打字机自我介绍，网格错落揭示技术栈，卡片光斑跟随指针。', 'Portfolio', 'Cyber', '个人主页,开发者主页', 90, '["starfield-drift-bg", "typewriter-caret", "stagger-grid-reveal", "spotlight-card"]', '[{"templateKey": "starfield-drift-bg", "stage": "背景", "role": "星空缓慢漂移，给深色页面一点呼吸"}, {"templateKey": "typewriter-caret", "stage": "内容", "role": "自我介绍逐字打出来，像终端在说话"}, {"templateKey": "stagger-grid-reveal", "stage": "滚动", "role": "技术栈网格错落点亮，每格差 0.06 秒"}, {"templateKey": "spotlight-card", "stage": "交互", "role": "项目卡在指针靠近时亮起光斑"}]', '做一个开发者主页：背景是缓慢漂移的星空；顶部用打字机效果逐字输出一句自我介绍并带光标闪烁；滚动到技术栈时网格逐格错落点亮（每格延迟 0.06 秒）；项目卡悬停出现跟随光斑。整体深色、等宽字体。', 'READY'),
	('studio-showcase', 'Studio Showcase', '工作室展示页：玻璃卡打底，倾斜反光给触感，团队与案例用模糊聚焦分批出现。', 'Portfolio', 'Glass', '工作室官网,团队主页', 90, '["glass-card-hover", "tilt-glare-card", "glass-lift-hover", "blur-focus-in"]', '[{"templateKey": "glass-card-hover", "stage": "内容", "role": "玻璃卡打底，一眼看出是「工作室」的气质"}, {"templateKey": "tilt-glare-card", "stage": "交互", "role": "案例卡随指针倾斜并点亮反光"}, {"templateKey": "glass-lift-hover", "stage": "交互", "role": "团队卡悬停浮起，与案例卡形成两种层级"}, {"templateKey": "blur-focus-in", "stage": "收尾", "role": "结尾的联系方式用模糊聚焦出现"}]', '做一个工作室展示页：内容用玻璃拟态卡片承载；案例卡随鼠标做三维倾斜并点亮高光；团队卡悬停上浮 8px；结尾的联系方式从模糊恢复到清晰。模糊只作用在卡片自身，避免整页 backdrop-filter 拖慢滚动。', 'READY'),
	('analytics-console', 'Analytics Console', '数据分析台：数字位翻滚呈现指标，网格错落铺开面板，点击有明确水波反馈。', 'Dashboard', 'Cyber', '数据看板,分析后台', 90, '["digit-roll-up", "stagger-grid-reveal", "scroll-progress-bar", "ripple-click-btn"]', '[{"templateKey": "digit-roll-up", "stage": "内容", "role": "核心指标逐位翻滚到目标值，先看数再看图"}, {"templateKey": "stagger-grid-reveal", "stage": "内容", "role": "分析面板错落铺开，避免整屏同时闪"}, {"templateKey": "scroll-progress-bar", "stage": "滚动", "role": "长报表用顶部进度条标出位置"}, {"templateKey": "ripple-click-btn", "stage": "交互", "role": "筛选按钮带水波反馈，点击后立即有回应"}]', '做一个数据分析台：顶部三个核心指标用数字位翻滚到目标值；下方面板错落出现（每块差 0.07 秒）；长报表顶部有滚动进度条；筛选按钮点击时从点击点扩散水波。数字滚动要在 0.9 秒内收敛并停住。', 'READY'),
	('ops-console', 'Ops Console', '运维控制台：面板转场切入，关键数字滚动，异常用弹入提示，弹窗用形变减少跳变感。', 'Dashboard', 'Glass', '运维后台,监控台', 87, '["page-transition", "dashboard-counter", "notification-popup", "modal-morph"]', '[{"templateKey": "page-transition", "stage": "内容", "role": "切换视图时面板整体切入，保持方位感"}, {"templateKey": "dashboard-counter", "stage": "内容", "role": "关键指标滚动到目标值，一眼看到变化"}, {"templateKey": "notification-popup", "stage": "交互", "role": "告警从右上角弹入，带一条进度指示"}, {"templateKey": "modal-morph", "stage": "收尾", "role": "查看详情时用形变弹窗，不切断当前上下文"}]', '做一个运维控制台：切换视图时面板从右侧整体切入淡入；关键指标在 0.8 秒内滚动到目标值；告警以右上角弹入方式出现并在 4 秒后自动收起；点击「详情」时弹窗由被点击的卡片形变展开。整体深色玻璃质感。', 'READY'),
	('minimal-report', 'Minimal Report', '极简报表页：只保留三件事——数字滚动、进度提示、一条完成通知。', 'Dashboard', 'Minimal', '报表页,周报看板', 89, '["dashboard-counter", "scroll-progress-bar", "notification-popup"]', '[{"templateKey": "dashboard-counter", "stage": "内容", "role": "数字滚动是这一页唯一的「主角动效」"}, {"templateKey": "scroll-progress-bar", "stage": "滚动", "role": "长报表给一个阅读进度，减少翻找"}, {"templateKey": "notification-popup", "stage": "收尾", "role": "加载完成只弹一条通知，不打断阅读"}]', '做一个极简报表页：核心数字在 0.8 秒内滚动到目标值；页面顶部有滚动进度条；数据加载完成后从右上角弹一条通知，4 秒后自动消失。除这三处外不要添加任何动画。', 'READY'),
	('game-login', 'Game Login', '游戏登录页：星空底 + 打字机标语，输入框流光待命，登录按钮按下有回弹。', 'Login', 'Cyber', '游戏登录页,电竞入口', 90, '["starfield-drift-bg", "typewriter-caret", "glow-border", "press-depth-card"]', '[{"templateKey": "starfield-drift-bg", "stage": "背景", "role": "星空漂移撑起「开场画面」的感觉"}, {"templateKey": "typewriter-caret", "stage": "内容", "role": "版本标语逐字打出，像游戏启动时的读取行"}, {"templateKey": "glow-border", "stage": "交互", "role": "输入框聚焦时边框流光，明确当前焦点"}, {"templateKey": "press-depth-card", "stage": "收尾", "role": "登录按钮按下时下沉再回弹，手感扎实"}]', '做一个游戏登录页：背景是缓慢漂移的星空；上方标语逐字打出并保留光标闪烁；输入框聚焦时边框流光扫过；登录按钮按下时下沉 2px 并在 250ms 内回弹。整体深色，霓虹只用在边框与按钮上。', 'READY'),
	('minimal-login', 'Minimal Login', '极简登录页：卡片整体浮入，输入框从模糊恢复，其余一切安静。', 'Login', 'Glass', '后台登录页,产品登录', 88, '["login-animation", "blur-reveal", "glow-border"]', '[{"templateKey": "login-animation", "stage": "内容", "role": "登录卡整体浮入，一次把结构交代清楚"}, {"templateKey": "blur-reveal", "stage": "内容", "role": "表单项从模糊恢复，视线自然落到第一个输入框"}, {"templateKey": "glow-border", "stage": "交互", "role": "提交按钮悬停时边框亮起，给一个轻反馈"}]', '做一个极简登录页：登录卡从下方 24px 上浮淡入；表单元素依次从 blur(8px) 恢复到清晰（每项延迟 0.08 秒）；提交按钮悬停时边框流光。整页只保留玻璃卡与一处渐变背景，不要其它装饰。', 'READY'),
	('esports-site', 'Esports Site', '电竞官网：三维场景开场 + 着色器波纹，赛程卡片按压回弹，点击有水波反馈。', 'Game UI', 'Cyber', '电竞官网,战队主页', 88, '["three-scene", "shader-background", "press-depth-card", "ripple-click-btn"]', '[{"templateKey": "three-scene", "stage": "背景", "role": "三维场景做开场，直接立住「大制作」的印象"}, {"templateKey": "shader-background", "stage": "背景", "role": "着色器波纹接住三维场景，滚动时不过于割裂"}, {"templateKey": "press-depth-card", "stage": "交互", "role": "赛程卡片按压回弹，模拟点按物理感"}, {"templateKey": "ripple-click-btn", "stage": "收尾", "role": "报名按钮点击扩散水波，反馈立刻可见"}]', '做一个电竞官网：首屏用 Three.js 场景开场，滚动后由着色器波纹背景接续；赛程卡片按下时下沉 2px、松开回弹；报名按钮点击时从点击点扩散水波。三维场景需提供降级方案，低端设备只保留静态首帧。', 'READY'),
	('game-loading', 'Game Loading Screen', '游戏加载界面：星空底上转着轨道方块，进度数字翻滚，底部一句话在上浮。', 'Game UI', 'Cyber', '加载界面,启动页', 89, '["starfield-drift-bg", "three-orbit-cubes", "digit-roll-up", "slide-up"]', '[{"templateKey": "starfield-drift-bg", "stage": "背景", "role": "星空漂移让等待过程不显得像卡住"}, {"templateKey": "three-orbit-cubes", "stage": "内容", "role": "轨道方块持续旋转，是最直接的「加载中」信号"}, {"templateKey": "digit-roll-up", "stage": "内容", "role": "进度数字翻滚，把等待量化"}, {"templateKey": "slide-up", "stage": "收尾", "role": "底部提示文案上浮淡入"}]', '做一个游戏加载界面：背景是缓慢漂移的星空；画面中央一组方块沿轨道持续旋转；进度以数字翻滚方式从 0 走到 100；底部提示文案上浮淡入。加载完成后所有动画同时淡出 200ms，不要硬切。', 'READY'),
	('match-lobby', 'Match Lobby', '对战大厅：着色器波纹撑底，玩家卡错落铺开，就位提示弹入，卡片按下有回弹。', 'Game UI', 'Cyber', '对战大厅,组队页', 89, '["shader-background", "stagger-grid-reveal", "press-depth-card", "notification-popup"]', '[{"templateKey": "shader-background", "stage": "背景", "role": "着色器波纹给大厅一点动态，但不抢信息"}, {"templateKey": "stagger-grid-reveal", "stage": "内容", "role": "玩家卡错落出现，每张差 0.06 秒"}, {"templateKey": "press-depth-card", "stage": "交互", "role": "准备按钮按下回弹，手感明确"}, {"templateKey": "notification-popup", "stage": "收尾", "role": "队友就位时右上角弹一条提示"}]', '做一个对战大厅：背景是低幅度的着色器波纹；玩家卡错落出现（每张延迟 0.06 秒）；准备按钮按下下沉并回弹；队友就位时右上角弹入提示并在 3 秒后收起。整体信息密度高，动效必须短（≤300ms）。', 'READY'),
	('jewelry-brand', 'Jewelry Brand', '珠宝品牌页：颗粒底压住反光，产品浮现交代形态，品牌名逐字上升，最后磁吸到购买。', 'Landing Page', 'Luxury', '珠宝品牌,高端电商', 90, '["grain-overlay-bg", "product-float-in", "split-char-rise", "magnetic-pull-btn"]', '[{"templateKey": "grain-overlay-bg", "stage": "背景", "role": "细颗粒底让金属反光不至于刺眼"}, {"templateKey": "product-float-in", "stage": "内容", "role": "产品以浮现方式出现，先把形态讲清楚"}, {"templateKey": "split-char-rise", "stage": "内容", "role": "品牌名逐字上升，节奏慢下来"}, {"templateKey": "magnetic-pull-btn", "stage": "收尾", "role": "购买按钮磁吸，明确唯一的行动点"}]', '做一个珠宝品牌页：背景铺细颗粒纹理；产品图从下方浮入并轻微放大；品牌名逐字上升；购买按钮带磁吸效果。整页只允许一处金属高光，节奏控制在 1.4 秒以上，避免廉价感。', 'READY'),
	('saas-pricing', 'SaaS Pricing', '定价页：段落柔和淡入，三张价格卡依次上浮悬停，主按钮滑出箭头，滚动提示可见。', 'AI SaaS', 'Minimal', '定价页,套餐对比', 91, '["smooth-fade", "pricing-card-hover", "arrow-swipe-btn", "scroll-hint-bounce"]', '[{"templateKey": "smooth-fade", "stage": "内容", "role": "顶部说明柔和淡入，不抢价格卡的注意力"}, {"templateKey": "pricing-card-hover", "stage": "交互", "role": "三张套餐卡悬停上浮，对比差异一眼可见"}, {"templateKey": "arrow-swipe-btn", "stage": "交互", "role": "主按钮箭头滑出，指明「下一步」"}, {"templateKey": "scroll-hint-bounce", "stage": "收尾", "role": "底部提示继续滚动，长页不留死角"}]', '做一个定价页：顶部说明文字柔和淡入；三张套餐卡悬停上浮 8px 并加深投影，被选中的那张边框高亮；主按钮悬停时箭头横向滑出；页面底部有一个轻微上下跳动的滚动提示。除选中态外不要改变卡片尺寸，避免布局抖动。', 'READY'),
	('startup-one-pager', 'Startup One-Pager', '创业一页纸：淡入 + 上滑两段式开场，特性卡错落铺开，底部给一个滚动提示收尾。', 'Landing Page', 'Minimal', '官网首页,创业一页纸', 91, '["smooth-fade", "slide-up", "card-stagger", "scroll-hint-bounce"]', '[{"templateKey": "smooth-fade", "stage": "背景", "role": "整页淡入，先把首帧的闪烁抹平"}, {"templateKey": "slide-up", "stage": "内容", "role": "标题与主按钮上滑出现，顺序明确"}, {"templateKey": "card-stagger", "stage": "内容", "role": "特性卡错落出现，每张差 0.09 秒"}, {"templateKey": "scroll-hint-bounce", "stage": "收尾", "role": "底部提示继续滚动，引导读完一页"}]', '做一个创业一页纸：整页淡入；主标题与按钮依次上滑（差 0.12 秒）；三到四张特性卡错落出现（每张差 0.09 秒）；底部有轻微跳动的滚动提示。全部动效在 1.2 秒内完成，只用 transform / opacity。', 'READY'),
	('hotel-booking', 'Hotel Booking', '预订流程页：玻璃卡承载表单，弹窗形变给出确认，通知弹入回报结果，点击有水波。', 'Landing Page', 'Glass', '预订页,订单流程', 89, '["glass-card-hover", "modal-morph", "ripple-click-btn", "notification-popup"]', '[{"templateKey": "glass-card-hover", "stage": "交互", "role": "房型卡用玻璃悬停，反馈轻且不打断选择"}, {"templateKey": "modal-morph", "stage": "内容", "role": "确认弹窗由被点击的卡片形变展开"}, {"templateKey": "ripple-click-btn", "stage": "交互", "role": "提交按钮点击扩散水波，明确「已提交」"}, {"templateKey": "notification-popup", "stage": "收尾", "role": "预订成功右上角弹入一条通知"}]', '做一个预订流程页：房型卡悬停上浮并微微提亮；点击「预订」时弹窗由该卡片形变展开；提交按钮点击时扩散水波；成功后右上角弹入通知并在 4 秒后收起。表单校验错误就地显示，不要用弹窗打断。', 'READY'),
	('creative-agency', 'Creative Agency', '创意机构首页：星系底撑场，标题擦除进入，光标跟随改成柔光，按钮磁吸收尾。', 'Landing Page', 'Cyber', '创意机构,品牌官网', 89, '["galaxy-background", "headline-clip-wipe", "cursor-follow", "magnetic-button"]', '[{"templateKey": "galaxy-background", "stage": "背景", "role": "星系渐变定调，给创意机构一点未来感"}, {"templateKey": "headline-clip-wipe", "stage": "内容", "role": "主标题擦除出现，比淡入更有主张"}, {"templateKey": "cursor-follow", "stage": "交互", "role": "光标跟随一团柔光，替代传统指针"}, {"templateKey": "magnetic-button", "stage": "收尾", "role": "「联系我们」磁吸，把转化点收住"}]', '做一个创意机构首页：背景是缓慢旋转的星系渐变；主标题从左向右擦除出现；鼠标移动时有一团 240px 的柔光跟随（指针设备才启用）；联系按钮带磁吸效果。整页只有背景一处高饱和，其它保持低饱和。', 'READY'),
	('premium-hero', 'Premium Hero', '首屏三件套：极光背景铺氛围、粒子星网给纵深、标题揭示出现，最后用磁吸按钮收住视线。', 'Landing Page', 'Luxury', '官网首页,AI 产品页', 89, '["aurora-background", "particle-network", "text-reveal", "magnetic-button"]', '[{"templateKey": "aurora-background", "stage": "背景", "role": "极光渐变铺氛围，先把画面质感定下来"}, {"templateKey": "particle-network", "stage": "背景", "role": "粒子星网给首屏纵深，避免背景是一张平面"}, {"templateKey": "text-reveal", "stage": "内容", "role": "主标题揭示出现，把视线带到内容"}, {"templateKey": "magnetic-button", "stage": "收尾", "role": "主按钮磁吸跟随，收住视线并引导点击"}]', '做一个高级感首屏：背景是缓慢漂移的极光渐变，上面叠一层粒子星网；主标题用 clip-path 从下向上揭示，主按钮带磁吸效果。整体节奏 1.2 秒内完成入场，不要同时出现。', 'READY'),
	('luxury-product-card', 'Luxury Product Card', '产品卡三件套：三维倾斜给触感、玻璃悬停给反馈、轻微浮动让静止状态也有呼吸。', 'Portfolio', 'Luxury', '个人作品集,官网首页', 90, '["floating-card", "tilt-card-3d", "glass-card-hover"]', '[{"templateKey": "floating-card", "stage": "背景", "role": "静止状态轻微浮动，让卡片一直「活着」"}, {"templateKey": "tilt-card-3d", "stage": "交互", "role": "随指针做三维倾斜，给出实体触感"}, {"templateKey": "glass-card-hover", "stage": "交互", "role": "玻璃悬停 + 亮边框，明确「可交互」"}]', '做一个产品卡片：静止时轻微上下浮动；鼠标移入时随指针做三维倾斜并点亮高光；卡片本身用玻璃拟态 + 1px 亮边框，悬停时上浮 8px。', 'READY'),
	('ai-saas-landing', 'AI SaaS Landing', 'AI 产品首页的完整配方：网格渐变底、浮动光球做视觉锚点、内容柔和淡入、边框流光提示可交互。', 'AI SaaS', 'Cyber', 'AI 产品页,官网首页', 90, '["mesh-gradient", "floating-orb", "smooth-fade", "glow-border", "magnetic-button"]', '[{"templateKey": "mesh-gradient", "stage": "背景", "role": "网格渐变打底，科技感来自结构"}, {"templateKey": "floating-orb", "stage": "背景", "role": "浮动光球当视觉锚点，让视线有落点"}, {"templateKey": "smooth-fade", "stage": "内容", "role": "文案柔和淡入，一次只动一个层级"}, {"templateKey": "glow-border", "stage": "交互", "role": "特性卡边框流光，提示可交互"}, {"templateKey": "magnetic-button", "stage": "收尾", "role": "主按钮磁吸，明确唯一的行动点"}]', '做 AI 产品首页：背景是网格渐变，中央一颗浮动光球作为视觉锚点；下方三个特性卡带流光描边，文案依次淡入，主按钮磁吸；整体冷静、有科技感，不要花哨。', 'READY'),
	('portfolio-opening', 'Portfolio Opening', '作品集开场：标题揭示 → 光斑跟随光标 → 作品卡缩放浮现，三段式把注意力从名字带到作品。', 'Portfolio', 'Minimal', '个人作品集', 89, '["text-reveal", "cursor-follow", "scale-reveal"]', '[{"templateKey": "text-reveal", "stage": "内容", "role": "先揭示名字标题，交代「这是谁」"}, {"templateKey": "cursor-follow", "stage": "交互", "role": "柔光跟随光标，把浏览变成一种手感"}, {"templateKey": "scale-reveal", "stage": "收尾", "role": "作品卡缩放浮现，把注意力交到作品上"}]', '做个人作品集开场：先揭示名字标题，然后一团柔光跟随鼠标，最后作品卡从 0.92 缩放浮现；整体克制，只保留必要动效，让别人记住作品而不是特效。', 'READY'),
	('dashboard-boot', 'Dashboard Boot', '后台开屏：面板从右侧切入、卡片错落出现、关键数字滚动到目标值，最后弹一条完成通知。', 'Dashboard', 'Minimal', '后台系统,数据看板', 89, '["page-transition", "card-stagger", "dashboard-counter", "notification-popup"]', '[{"templateKey": "page-transition", "stage": "内容", "role": "面板从右侧切入淡入，先建立方位感"}, {"templateKey": "card-stagger", "stage": "内容", "role": "统计卡片错落出现，每张差 0.09 秒"}, {"templateKey": "dashboard-counter", "stage": "内容", "role": "核心数字滚动到目标值，一眼看到变化"}, {"templateKey": "notification-popup", "stage": "收尾", "role": "全部完成后弹一条通知，收束整个过程"}]', '做后台开屏：内容面板从右滑入淡入，统计卡片错落出现（每张差 0.09 秒），核心数字从 0 滚动到目标值，全部完成后右上角弹一条通知。整体不超过 2 秒。', 'READY')
ON DUPLICATE KEY UPDATE
	`name` = VALUES(`name`), `description` = VALUES(`description`), `scene` = VALUES(`scene`),
	`style` = VALUES(`style`), `best_for` = VALUES(`best_for`), `score` = VALUES(`score`),
	`template_keys` = VALUES(`template_keys`), `steps` = VALUES(`steps`), `prompt` = VALUES(`prompt`);
